### ISSUE TITLE
reset_admin.sh 

### ISSUE THREAD

**Issue by LateNightIceCream** [ggogel/seafile-containerized#74]
The script `/opt/seafile/seafile-server-latest/reset_admin.sh` inside seafile-server throws an error:

```
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-9.0.10/seahub/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/seafile/seafile-server-9.0.10/seahub/thirdpart/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/seafile/seafile-server-9.0.10/seahub/thirdpart/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/opt/seafile/seafile-server-9.0.10/seahub/thirdpart/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/seafile/seafile-server-9.0.10/seahub/thirdpart/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/seafile/seafile-server-9.0.10/seahub/thirdpart/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'captcha'
```

This seems to be a missing python dependency

EDIT:
Ok, my bad. I see that the seahub container has those dependencies but not the script. I suppose this is on purpose? 
My problem is that I cannot do my initial login with the admin credentials supplied in docker-compose.yml after deployment. This also didn't work on the regular seafile installation but running the reset_admin.sh script fixed it.

**Comment by LateNightIceCream** [comment]
Thank you! That worked beautifully :))
