### ISSUE TITLE
building on oci/arm64

### ISSUE THREAD

**Issue by eleaner** [ggogel/seafile-containerized#77]
Hi,

I tried to build the images on arm64, but I ended up with this error, any ideas on how to fix it?

```
seafile-server     | Starting seafile server, please wait ...
seafile-server     | /opt/seafile/seafile-server-9.0.10/seafile.sh: line 143: /opt/seafile/seafile-server-9.0.10/seafile/bin/seafile-controller: cannot execute binary file: Exec format error
seafile-seahub     |
seafile-seahub     | LC_ALL is not set in ENV, set to en_US.UTF-8
seafile-seahub     | Starting seahub at port 8000 ...
seafile-seahub     |
seafile-seahub     | Error happened during creating seafile admin.
seafile-seahub     |
seafile-server     | Traceback (most recent call last):
seafile-server     |   File "/scripts/start.py", line 66, in <module>
seafile-server     |     main()
seafile-server     |   File "/scripts/start.py", line 55, in main
seafile-server     |     call('{} start'.format(get_script('seafile.sh')))
seafile-server     |   File "/scripts/utils/__init__.py", line 70, in call
seafile-server     |     return subprocess.check_call(*a, **kw)
seafile-server     |   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
seafile-server     |     raise CalledProcessError(retcode, cmd)
seafile-server     | subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-9.0.10/seafile.sh start' returned non-zero exit status 1.
seafile-server     | Failed to start seafile server
seafile-seahub     |
seafile-seahub     | Seahub is not running
seafile-seahub     | Done.
```

**Comment by eleaner** [comment]
Ah, I think I see.
The dockerfile downloads AMD64 binaries, so they obviously do not work

that's a shame

**Comment by ggogel** [comment]
Hi, 

yes, the binaries are not compiled. It's simply downloading the official Linux Server package from the website.

As far as I know there still no official ARM binaries, right?

Were you able to find a workaround?

**Comment by eleaner** [comment]
Yes, but far from ideal, as I really like your idea of building proper docker containers.
I started using this: https://github.com/ChatDeBlofeld/seafile-arm-docker-base.git
but I was not able to merge it with your project

**Comment by eleaner** [comment]
the lack of official arm image is actually a bigger issue than I thought
my backend is S3, I could use pro but it won't fork on oracle cloud :(
